apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - template-require-non-root.yaml
  - template-require-resources.yaml
  - template-disallow-latest-tag.yaml
  - template-drop-capabilities.yaml
  - constraints.yaml
